from __future__ import annotations

SAMPLE_REDDIT_ITEMS = [
    {
        "source_url": "https://reddit.com/r/dogs/example1",
        "subreddit": "r/dogs",
        "post_id": "dogs_001",
        "comment_id": None,
        "title": "Is there an app for tracking dog medication schedules?",
        "body": "I am tired of using a spreadsheet for my senior dog's pills. I would pay for reminders that work for two caretakers.",
        "score": 42,
        "comment_count": 18,
        "created_at": "2026-05-08T01:00:00+00:00",
        "language": "en",
    },
    {
        "source_url": "https://reddit.com/r/AskVet/example2",
        "subreddit": "r/AskVet",
        "post_id": "vet_002",
        "comment_id": None,
        "title": "How do people deal with complicated pet medication routines?",
        "body": "Our cat has morning and evening meds and the current apps are annoying. Does anyone else have this problem?",
        "score": 31,
        "comment_count": 24,
        "created_at": "2026-05-08T02:00:00+00:00",
        "language": "en",
    },
    {
        "source_url": "https://reddit.com/r/Parenting/example3",
        "subreddit": "r/Parenting",
        "post_id": "parent_003",
        "comment_id": None,
        "title": "Why is it so hard to plan lunchboxes for picky kids?",
        "body": "I wish there was a weekly planner that remembers what my children actually eat and makes a shopping list.",
        "score": 88,
        "comment_count": 67,
        "created_at": "2026-05-08T03:00:00+00:00",
        "language": "en",
    },
    {
        "source_url": "https://reddit.com/r/MealPrepSunday/example4",
        "subreddit": "r/MealPrepSunday",
        "post_id": "meal_004",
        "comment_id": None,
        "title": "Any alternatives to Pinterest boards for school lunch planning?",
        "body": "Pinterest is too manual. I want a simple app or printable system for picky eater lunches in the US.",
        "score": 63,
        "comment_count": 33,
        "created_at": "2026-05-08T04:00:00+00:00",
        "language": "en",
    },
]
